
# api key
api_key: "9ccfa3d4400a4ac7b31b3c5fc161a7fc"

# merchant private key
merchant_private_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9unpFVUDstwQY
  PRj7HjnW3kiLKnFE4E8AujM0/pjsPU2FVHYGbyhqFrXWknwTJ0GCWgHIf5utpb/Z
  xflljq7e+9EogSW1D5MEBKXrNFlkQJAhupzE3mdrsA3Gq0gTYokRQhQGo8MAxzWF
  ObVEotWpzUfraGtH3sfVZ71uM+773pwLGZtCwbayIRjhdH9SO+00O0rRU40cbAgO
  J/+bYjlvtGslIEhvxCTIwAMjHnj7HGb+kOBPt82cvYjF9KuJKKJmG7PcdJufFYD2
  /3YYcAsbpK5cNffPWUw2Ai+3nvqAdslo+0bhVilFnD39Luyt3ESJKe6KavHfSQoW
  FhRlLHq3AgMBAAECggEBAK0J8pJhmwFKOhXRQ4NkoePyf79NSllDK0rCiAmBWv+7
  OYSs76gWoYmAhP/aQgdF+l1ksdOnbtkFHuEDyt5xL9R3Xt/OShHEzpUPmDPYXt8s
  c0gP5wM2xKRWwXm8pdPoPpLa7WDQ4v1Gsu17IHQk/zIK49k0NwQpj6B3KTHlc8WK
  QcwdG7uI+s2X9ggGdh7SoecCkQk/Nj+aJaU070ffrnHoClPbB54bcktDSn8C3OLu
  4h7CM/IY+9ycDj7rP1I9heK7Neh8R9a+Ef+XZ+dQWi3npYEN1yClS+F1uYRanwmb
  CZmAgW+pCFTMK8gSgdppI19UkUQk94agSof6teAayoECgYEA9meddtVV9JcPfgRP
  JBD2VBLfMG/bcvrXiOpb+ZlIotg4Guvk00IMQ/dz99j98S3l5P9mG0Z4zNOv3l/x
  RRE+mdX5H5FY7Qx7jb0yQAMuZojIKClzClohZFqfyzpJ0qftn5Au62WoRTrcHgdA
  nzLUqan7rxb0sYa/zO85jdovI5ECgYEAxR3coQqIh5KV1Fut1ghohtf7fy9Syo8n
  NS9MaCcTIwOX8idKG460iSjrU+a5BVGBYuDgcMN/qsbt7OQqTAK2T+YL01bv0r30
  JUt5v1kmBSLCrMaprLBsiD/5pz5AvLhNU1rWJOaNxM2NvOL5LE8+x1xqBJ4TgVhz
  gsYuedp2BccCgYBXOw1KwXGhmkzYvuvJh9u8ncW3nxHgXZ8qEFWpQjOtur/5/+LN
  S0eOVC8Q4hfcZvRJIoViSIuBb7uGDQ8b9WPlEBQWsdz6Zn3jCsScVsP5dpjtZucc
  FhZWMaL6TlNOKTb9UwzZNu7gO1srokOlWFhjDBNWw9iydFK4WURVzJT9kQKBgAvL
  EpUr/SknUwGGjqr8i8xthaWBXlGyKOVctBSTKejxYRji0uM9MX33TcUSS8WOr9AL
  pkH44F2GU1vV9tXfX6r+F30IeYbBSKcmkd0p50VtY/pUVHh5gbTRJw2jgtoHqNCw
  4ZkJljfNGIrRhZjqENZ6p/kowAAAG8EaPFOcB22nAoGAMlBl/7XiJsQgWZ5yxxIn
  3COyn/1aG5v6fwT2si6eXhklbZzwL3xCWBgNM92KPGpnEVgxacVhPB8Ka2s5ebgB
  g0OIsMyvd7uJIsClXhONEvlXynlV3DnDDj65b1sogsUURaJ1VzdsraUm5+Q+SJEB
  IZJP+o9bpMu2/j7Hbh+rKhg=
  -----END PRIVATE KEY-----

# platform public key
platform_public_key: |
  -----BEGIN RSA PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvNUD/VvNYPl5uCCJoDPi
  RlpZHjXkcQigySy0Z+GJJJKV92ocRSjD20W4Rs2LRS+E+T+3cjCTtnZB8iF9VFi+
  zOk0evwWeUg5ZrOORWkNV9RIX6YWX5T7TC5hKFNVKuMDULy5Lgbk9hFa4IO7lA7X
  92/XQSZhAORpofRau+AtS8Dm/MbmeSYatviGKk9JJByYIcuC8yIobdb+8L3Q8WeE
  vKbLgh9/74Ie9LuYlCznvRB2z39MFxWy7gXNjMdHobo5McxdblzcPMkYTwkuHLoH
  tLgoDk1iaQElnz5Ce02CfLPN3AQLByrLp/1NaaFKCA3ok+/QOzunBvDYmiqfPrFp
  8QIDAQAB
  -----END RSA PUBLIC KEY-----
